# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f1a286d59189af0e80e0bc76facb25e03506b4efe4f1219499fcbba5767bdb77fefbf52b01086b351238dace3f0f1d0a3be539a88e94c4c08338cab580a1103

test:
  secret_key_base: cb20c265a4c795d825e9e53cf1a11d44b8b093987bfdd807a2bfc886f408b8fc3e41343eacd0b2b49f0059293db944ff8af49cf9ce7ddb4542422d6585779185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
