---
development:
  cloud_name: db5orfik4
  api_key: '344698462367118'
  api_secret: zRfkQzo8hmpMtSxjt-eSqrKv4Ss
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: db5orfik4
  api_key: '344698462367118'
  api_secret: zRfkQzo8hmpMtSxjt-eSqrKv4Ss
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: db5orfik4
  api_key: '344698462367118'
  api_secret: zRfkQzo8hmpMtSxjt-eSqrKv4Ss
  enhance_image_tag: true
  static_image_support: false
